FROM kmtsui/geant4.10.3.3

RUN echo "Hello from inside the container" && \
    echo "Base image is from docker://kmtsui/geant4.10.3.3" && \ 
    echo "Install eos dependencies" && \
    apt-get -y update && apt-get -y upgrade && \ 
    apt-get -y install lsb-release curl gnupg2 && \
    echo "Configure APT repositories to install the software" && \
    curl -sL http://storage-ci.web.cern.ch/storage-ci/storageci.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/storage-ci.gpg && \
    echo "deb [arch=$(dpkg --print-architecture)] http://storage-ci.web.cern.ch/storage-ci/debian/xrootd/ $(lsb_release -cs) release" | tee -a /etc/apt/sources.list.d/cerneos-client.list > /dev/null && \
    echo "deb [arch=$(dpkg --print-architecture)] http://storage-ci.web.cern.ch/storage-ci/debian/eos/diopside/ $(lsb_release -cs) tag" | tee -a /etc/apt/sources.list.d/cerneos-client.list > /dev/null && \
    echo "Package: xrootd* libxrd* libxrootd*\nPin: version 5.5.5\nPin-Priority: 1000" > /etc/apt/preferences.d/xrootd.pref && \
    echo "Install eos-fusex" && \
    apt-get -y update && apt-get -y install eos-fusex && \
    echo "Setup conf and dir" && \
    echo '{"name":"project-w","hostport":"eosproject-w.cern.ch","remotemountdir":"/eos/project/w/"}' > /etc/eos/fuse.project-w.conf && more /etc/eos/fuse.project-w.conf && \
    mkdir /eos && eosxd -ofsname=project-w && ls -lh /eos